version: "2.3"

services:
  server:
    container_name: "api_server"
    build:
      context: "."
    ports:
      - "5000:5000"
    depends_on:
      - "db"
    environment:
      DOTENV_PATH: .env
  db:
    container_name: "api_db"
    image: "mongo:5.0.6"
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - "./mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: auth
