import { Dimensions, Platform, StyleSheet } from "react-native";

let { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  appBar: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: 10,
    paddingRight: 10,
    elevation: 5,
  },
  cameraOverlayContainer: {
    position: "absolute",
    width: "100%",
    height: "100%",
    backgroundColor: "transparent",
    borderColor: "black",
    opacity: 0.3,
  },
  cameraCenter: {
    width: width * 0.8,
    height: width * 0.8,
    justifyContent: "flex-end",
    alignItems: "center",
    backgroundColor: "transparent",
    elevation: Platform.OS === "android" ? 50 : 0,
  },
  cameraActionButtons: {
    width: "100%",
    height: "100%",
    padding: 10,
    alignContent: "center",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    elevation: Platform.OS === "android" ? 50 : 0,
  },
  cameraCloseButton: {
    width: 150,
    alignSelf: "flex-end",
    alignItems: "center",
    backgroundColor: "#fff",
    padding: 10,
    borderRadius: 5,
    backgroundColor: "#2196f3",
  },
  addServiceButton: {
    display: "flex",
    alignSelf: "flex-end",
    alignItems: "flex-end",
    backgroundColor: "#fff",
    padding: 10,
    elevation: 10,
    borderRadius: 5,
  },
  text: {
    fontSize: 14,
    color: "black",
  },
  camera: {
    flex: 1,
    alignItems: "center",
    width: "100%",
    height: "100%",
  },
  body: {
    flex: 1,
    width: "100%",
    backgroundColor: "#e0e0e0",
    alignItems: "center",
    padding: 10,
  },
  textInput: {
    width: "100%",
    height: 40,
    borderColor: "gray",
    borderWidth: 1,
    marginBottom: 10,
    padding: 5,
    borderRadius: 5,
    flex: 1,
    marginRight: 10,
  },

  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    margin: "auto",
  },
  modalView: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    margin: 20,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: "80%",
  },
  buttonOpen: {
    width: "100%",
    backgroundColor: "#F194FF",
  },
  buttonClose: {
    backgroundColor: "#2196F3",
  },
  button: {
    marginTop: 5,
    padding: 8,
    borderRadius: 5,
  },
  textStyle: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
  },
  modalText: {
    textAlign: "center",
    backgroundColor: "#0005",
    borderRadius: 5,
  },
  vpin: {
    borderBottomColor: "#000",
    borderBottomWidth: 1,
    width: "100%",
    height: 40,
    borderColor: "gray",
    marginBottom: 10,
    padding: 5,
    borderRadius: 5,
    flex: 1,
    marginRight: 10,
  },
  loginCenterContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "center",
    width: "80%",
    height: 400,
    borderRadius: 20,
    backgroundColor: "#eee",
    padding: 20,
    elevation: 5,
  },
  loginInput: {
    width: "100%",
    height: 40,
    minHeight: 40,
    maxHeight: 40,
    borderColor: "gray",
    borderWidth: 1,
    marginBottom: 10,
    padding: 5,
    borderRadius: 5,
    flex: 1,
    backgroundColor: "#fff",
  },
});
